# goal
string dock_frame
string robot_dock_frame
float32 dock_offset
int8 retries
---
# result
robotnik_common_msgs/Response response
---
# feedback
int8 try_number
string status
geometry_msgs/Pose2D remaining_distance
float32 time_in_action
float32 time_in_step